language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t birjik97/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true birjik97/react-test npm test -- --coverage

after_success:
  - docker build -t birjik97/multi-client ./client
  - docker build -t birjik97/multi-nginx ./nginx
  - docker build -t birjik97/multi-server ./server
  - docker build -t birjik97/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push birjik97/multi-client
  - docker push birjik97/multi-nginx
  - docker push birjik97/multi-server
  - docker push birjik97/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-923445559289"
  bucket_path: "docker-multi"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY